---
- name: Print message to localhost
  hosts: localhost
  tasks:
    - name: Print a message
      debug:
        msg: "Hello, this is a message from Ansible!"
    - name: Print the user-supplied variable
      debug:
        msg: "The value of user_variable is: {{ cics }}"
